#!/usr/bin/env bash
set -euo pipefail

# Show recent shell task logs generated by Vegvisir.
# Usage: ./vshell-logs.sh [limit]

limit="${1:-10}"
find .vegvisir/tasks -type f -name 'shell-*.log' 2>/dev/null | sort -r | head -n "$limit"
