use crate::ingest::hex_hash;
use crate::models::*;
use anyhow::{Context, Result, bail};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

pub fn write_bundle(bundle: &SkillBundle, out: &Path) -> Result<()> {
    fs::create_dir_all(out.join("skills"))?;
    fs::create_dir_all(out.join("sources"))?;
    fs::create_dir_all(out.join("graph"))?;
    fs::create_dir_all(out.join("audit"))?;
    write_yaml(&out.join("package.yaml"), &bundle.package)?;
    write_yaml(&out.join("sources/index.yaml"), &bundle.sources)?;
    write_yaml(&out.join("sources/sections.yaml"), &bundle.sections)?;
    write_yaml(&out.join("candidates.yaml"), &bundle.capability_candidates)?;
    write_yaml(&out.join("graph/concepts.yaml"), &bundle.graph.concepts)?;
    write_yaml(
        &out.join("graph/dependencies.yaml"),
        &bundle.graph.dependencies,
    )?;
    write_yaml(&out.join("audit/events.yaml"), &bundle.audit_events)?;
    write_yaml(&out.join("forge_requests.yaml"), &bundle.forge_requests)?;
    write_yaml(&out.join("forge_responses.yaml"), &bundle.forge_responses)?;
    for skill in &bundle.skills {
        write_yaml(
            &out.join("skills").join(format!("{}.yaml", skill.id)),
            skill,
        )?;
    }
    fs::write(
        out.join("README.md"),
        format!("# {}\n\nGenerated by Skiller Rust.\n", bundle.package.name),
    )?;
    write_manifest(out)?;
    Ok(())
}

pub fn read_bundle(path: &Path) -> Result<SkillBundle> {
    let package: SkillPackage = read_yaml(&path.join("package.yaml"))?;
    let sources: Vec<SourceDocument> =
        read_yaml(&path.join("sources/index.yaml")).unwrap_or_default();
    let sections: Vec<DocumentSection> =
        read_yaml(&path.join("sources/sections.yaml")).unwrap_or_default();
    let concepts: Vec<ConceptNode> =
        read_yaml(&path.join("graph/concepts.yaml")).unwrap_or_default();
    let dependencies: Vec<SkillDependency> =
        read_yaml(&path.join("graph/dependencies.yaml")).unwrap_or_default();
    let audit_events: Vec<AuditEvent> =
        read_yaml(&path.join("audit/events.yaml")).unwrap_or_default();
    let capability_candidates: Vec<CapabilityCandidate> =
        read_yaml(&path.join("candidates.yaml")).unwrap_or_default();
    let forge_requests: Vec<ForgeRequestEnvelope> =
        read_yaml(&path.join("forge_requests.yaml")).unwrap_or_default();
    let forge_responses: Vec<ForgeResponseEnvelope> =
        read_yaml(&path.join("forge_responses.yaml")).unwrap_or_default();
    let mut skills = Vec::new();
    for entry in fs::read_dir(path.join("skills")).with_context(|| "read skills directory")? {
        let entry = entry?;
        if entry.path().extension().and_then(|s| s.to_str()) == Some("yaml") {
            skills.push(read_yaml(&entry.path())?);
        }
    }
    Ok(SkillBundle {
        package,
        sources,
        sections,
        capability_candidates,
        skills,
        graph: SkillGraph {
            dependencies,
            related: vec![],
            concepts,
        },
        audit_events,
        forge_requests,
        forge_responses,
    })
}

#[derive(Debug, Serialize)]
pub struct ValidationReport {
    pub valid: bool,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}
pub fn validate_bundle(bundle: &SkillBundle) -> ValidationReport {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    if bundle.skills.is_empty() {
        errors.push("bundle contains no skills".into());
    }
    let section_ids: std::collections::BTreeSet<_> = bundle
        .sections
        .iter()
        .map(|s| s.section_id.as_str())
        .collect();
    if let Err(err) = crate::forge::validate_stored_forge(bundle) {
        errors.push(err.to_string());
    }
    for skill in &bundle.skills {
        if skill.citations.is_empty() {
            errors.push(format!("{} has no citations", skill.id));
        }
        if crate::security::contains_secret_like_content(
            &serde_yaml::to_string(skill).unwrap_or_default(),
        ) {
            errors.push(format!("{} contains secret-like content", skill.id));
        }
        for sid in &skill.source_section_ids {
            if !section_ids.contains(sid.as_str()) {
                errors.push(format!("{} references missing section {}", skill.id, sid));
            }
        }
        if skill.evidence_breakdown.speculative_candidate > 0.4
            && skill.status == SkillStatus::Published
        {
            errors.push(format!(
                "{} is published with high speculative evidence",
                skill.id
            ));
        }
        if skill.runtime_policy.modify_external_systems
            && !skill.runtime_policy.requires_user_approval
        {
            errors.push(format!(
                "{} can modify external systems without approval",
                skill.id
            ));
        }
        if skill.confidence.raw < 0.35 {
            warnings.push(format!("{} has low confidence", skill.id));
        }
    }
    ValidationReport {
        valid: errors.is_empty(),
        errors,
        warnings,
    }
}

#[derive(Debug, Serialize)]
pub struct EvalReport {
    pub passed: bool,
    pub checks: Vec<String>,
    pub failures: Vec<String>,
}
pub fn eval_bundle(bundle: &SkillBundle) -> EvalReport {
    let v = validate_bundle(bundle);
    EvalReport {
        passed: v.valid,
        checks: vec![
            "schema/reference validation".into(),
            "citation presence".into(),
            "publication safety".into(),
        ],
        failures: v.errors,
    }
}

#[derive(Debug, Serialize)]
pub struct ReadinessReport {
    pub ready: bool,
    pub blockers: Vec<String>,
    pub warnings: Vec<String>,
    pub skill_count: usize,
}
pub fn readiness_report(bundle: &SkillBundle) -> ReadinessReport {
    let validation = validate_bundle(bundle);
    let mut blockers = validation.errors;
    for s in &bundle.skills {
        if matches!(
            s.status,
            SkillStatus::Draft | SkillStatus::Candidate | SkillStatus::NeedsReview
        ) {
            blockers.push(format!("{} is not reviewed/approved", s.id));
        }
    }
    ReadinessReport {
        ready: blockers.is_empty(),
        blockers,
        warnings: validation.warnings,
        skill_count: bundle.skills.len(),
    }
}

pub fn publish_bundle(bundle: &SkillBundle, registry: &Path, force: bool) -> Result<()> {
    let readiness = readiness_report(bundle);
    if !readiness.ready && !force {
        bail!("bundle is not publication-ready; rerun with --force only after review");
    }
    let dest = registry
        .join(&bundle.package.bundle_id)
        .join(&bundle.package.version);
    write_bundle(bundle, &dest)?;
    fs::write(
        dest.join("PROVENANCE.json"),
        serde_json::to_string_pretty(
            &serde_json::json!({"published_at": Utc::now(), "force": force, "warnings": readiness.warnings, "blockers": readiness.blockers}),
        )?,
    )?;
    write_manifest(&dest)?;
    write_registry_index(registry)?;
    Ok(())
}

#[derive(Debug, Serialize)]
pub struct RegistryEntry {
    pub bundle_id: String,
    pub name: String,
    pub version: String,
    pub domain: Option<String>,
    pub path: PathBuf,
    pub skill_count: usize,
    pub published_at: Option<String>,
    pub manifest_valid: bool,
    pub deprecated: bool,
    pub deprecation_reason: Option<String>,
    pub active_version: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct RegistryIndex {
    pub generated_at: chrono::DateTime<Utc>,
    pub registry_path: PathBuf,
    pub entries: Vec<RegistryEntry>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct DeprecationRecord {
    pub bundle_id: String,
    pub version: String,
    pub deprecated_at: chrono::DateTime<Utc>,
    pub reason: String,
    pub replacement_version: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RollbackRecord {
    pub bundle_id: String,
    pub active_version: String,
    pub rolled_back_at: chrono::DateTime<Utc>,
    pub reason: String,
}

#[derive(Debug, Serialize)]
pub struct ManifestVerificationReport {
    pub valid: bool,
    pub checked_files: usize,
    pub missing_files: Vec<String>,
    pub changed_files: Vec<String>,
    pub extra_files: Vec<String>,
    pub malformed_lines: Vec<String>,
}

pub fn list_registry(registry: &Path) -> Result<RegistryIndex> {
    let mut entries = Vec::new();
    if !registry.exists() {
        return Ok(RegistryIndex {
            generated_at: Utc::now(),
            registry_path: registry.to_path_buf(),
            entries,
        });
    }

    for bundle_dir in
        fs::read_dir(registry).with_context(|| format!("read {}", registry.display()))?
    {
        let bundle_dir = bundle_dir?;
        if !bundle_dir.file_type()?.is_dir() {
            continue;
        }
        for version_dir in fs::read_dir(bundle_dir.path())? {
            let version_dir = version_dir?;
            if !version_dir.file_type()?.is_dir() {
                continue;
            }
            let path = version_dir.path();
            let package_path = path.join("package.yaml");
            if !package_path.exists() {
                continue;
            }
            let package: SkillPackage = read_yaml(&package_path)?;
            let skill_count = fs::read_dir(path.join("skills"))
                .map(|entries| {
                    entries
                        .filter_map(Result::ok)
                        .filter(|entry| {
                            entry.path().extension().and_then(|s| s.to_str()) == Some("yaml")
                        })
                        .count()
                })
                .unwrap_or(0);
            let provenance_path = path.join("PROVENANCE.json");
            let published_at = fs::read_to_string(&provenance_path)
                .ok()
                .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
                .and_then(|value| value.get("published_at").map(|v| v.to_string()));
            let manifest_valid = verify_manifest(&path)
                .map(|report| report.valid)
                .unwrap_or(false);
            let deprecation: Option<DeprecationRecord> =
                read_yaml(&path.join("DEPRECATION.yaml")).ok();
            let rollback: Option<RollbackRecord> =
                read_yaml(&bundle_dir.path().join("ROLLBACK.yaml")).ok();
            entries.push(RegistryEntry {
                bundle_id: package.bundle_id,
                name: package.name,
                version: package.version,
                domain: package.domain,
                path,
                skill_count,
                published_at,
                manifest_valid,
                deprecated: deprecation.is_some(),
                deprecation_reason: deprecation.map(|d| d.reason),
                active_version: rollback.map(|r| r.active_version),
            });
        }
    }
    entries.sort_by(|a, b| {
        a.bundle_id
            .cmp(&b.bundle_id)
            .then(a.version.cmp(&b.version))
            .then(a.path.cmp(&b.path))
    });
    Ok(RegistryIndex {
        generated_at: Utc::now(),
        registry_path: registry.to_path_buf(),
        entries,
    })
}

pub fn write_registry_index(registry: &Path) -> Result<RegistryIndex> {
    fs::create_dir_all(registry)?;
    let index = list_registry(registry)?;
    write_yaml(&registry.join("index.yaml"), &index)?;
    Ok(index)
}

pub fn deprecate_registry_entry(
    registry: &Path,
    bundle_id: &str,
    version: &str,
    reason: &str,
    replacement_version: Option<&str>,
) -> Result<DeprecationRecord> {
    let entry = registry.join(bundle_id).join(version);
    if !entry.join("package.yaml").exists() {
        bail!("registry entry not found: {}/{}", bundle_id, version);
    }
    let record = DeprecationRecord {
        bundle_id: bundle_id.to_string(),
        version: version.to_string(),
        deprecated_at: Utc::now(),
        reason: reason.to_string(),
        replacement_version: replacement_version.map(str::to_string),
    };
    write_yaml(&entry.join("DEPRECATION.yaml"), &record)?;
    write_manifest(&entry)?;
    write_registry_index(registry)?;
    Ok(record)
}

pub fn rollback_registry_entry(
    registry: &Path,
    bundle_id: &str,
    to_version: &str,
    reason: &str,
) -> Result<RollbackRecord> {
    let bundle_root = registry.join(bundle_id);
    let target = bundle_root.join(to_version);
    if !target.join("package.yaml").exists() {
        bail!("rollback target not found: {}/{}", bundle_id, to_version);
    }
    let record = RollbackRecord {
        bundle_id: bundle_id.to_string(),
        active_version: to_version.to_string(),
        rolled_back_at: Utc::now(),
        reason: reason.to_string(),
    };
    write_yaml(&bundle_root.join("ROLLBACK.yaml"), &record)?;
    write_registry_index(registry)?;
    Ok(record)
}

pub fn verify_manifest(root: &Path) -> Result<ManifestVerificationReport> {
    let manifest_path = root.join("MANIFEST.sha256");
    let manifest = fs::read_to_string(&manifest_path)
        .with_context(|| format!("read {}", manifest_path.display()))?;
    let mut checked_files = 0usize;
    let mut missing_files = Vec::new();
    let mut changed_files = Vec::new();
    let mut malformed_lines = Vec::new();
    let mut expected_paths = std::collections::BTreeSet::new();

    for line in manifest.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let Some((hash, rel)) = line.split_once("  ") else {
            malformed_lines.push(line.to_string());
            continue;
        };
        if hash.len() != 64 || !hash.chars().all(|c| c.is_ascii_hexdigit()) {
            malformed_lines.push(line.to_string());
            continue;
        }
        let rel_path = PathBuf::from(rel);
        expected_paths.insert(rel_path.clone());
        let file_path = root.join(&rel_path);
        if !file_path.exists() {
            missing_files.push(rel.to_string());
            continue;
        }
        let bytes = fs::read(&file_path)?;
        checked_files += 1;
        if hex_hash(&bytes) != hash {
            changed_files.push(rel.to_string());
        }
    }

    let mut extra_files = Vec::new();
    for entry in walkdir::WalkDir::new(root)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file())
    {
        let path = entry.path();
        let rel = path.strip_prefix(root).unwrap().to_path_buf();
        if rel == PathBuf::from("MANIFEST.sha256") {
            continue;
        }
        if !expected_paths.contains(&rel) {
            extra_files.push(rel.display().to_string());
        }
    }
    extra_files.sort();

    Ok(ManifestVerificationReport {
        valid: missing_files.is_empty()
            && changed_files.is_empty()
            && extra_files.is_empty()
            && malformed_lines.is_empty(),
        checked_files,
        missing_files,
        changed_files,
        extra_files,
        malformed_lines,
    })
}

fn write_yaml<T: Serialize>(path: &Path, value: &T) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, serde_yaml::to_string(value)?)?;
    Ok(())
}
fn read_yaml<T: for<'de> serde::Deserialize<'de>>(path: &Path) -> Result<T> {
    Ok(serde_yaml::from_str(
        &fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?,
    )?)
}
fn write_manifest(root: &Path) -> Result<()> {
    let mut lines = Vec::new();
    for entry in walkdir::WalkDir::new(root)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file())
    {
        let path = entry.path();
        if path.file_name().and_then(|s| s.to_str()) == Some("MANIFEST.sha256") {
            continue;
        }
        let rel = path.strip_prefix(root).unwrap();
        let bytes = fs::read(path)?;
        lines.push(format!("{}  {}", hex_hash(&bytes), rel.display()));
    }
    lines.sort();
    fs::write(root.join("MANIFEST.sha256"), lines.join("\n"))?;
    Ok(())
}
