[package]
name = "msp-server"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
msp-core = { path = "../msp-core" }
msp-registry = { path = "../msp-registry" }
serde.workspace = true
serde_json.workspace = true
